export const arrayOfProducts = [
    { name: 'Tost hleb', category: 'peciva', price: '40 rsd', image: 'bakinhleb.jpg' }, 
    { name: 'Bakin hleb', category: 'peciva', price: '200e', image: 'tosthleb.jpg' },
    { name: 'Razeni hleb', category: 'peciva', price: '900 rsd', image: 'razenihleb.jpg' },
    { name: 'Beli hleb', category: 'peciva', price: '40 rsd', image: 'belihleb.jpg' },
    { name: 'Razeni hleb', category: 'peciva', price: '40rsd', image: 'kiflice-maslina.jpg' },
    { name: 'Tost hleb', category: 'peciva', price: '40 rsd', image: 'bakinhleb.jpg' }, 
    { name: 'Bakin hleb', category: 'peciva', price: '200e', image: 'tosthleb.jpg' },
    { name: 'Razeni hleb', category: 'peciva', price: '900 rsd', image: 'razenihleb.jpg' },
    { name: 'Beli hleb', category: 'peciva', price: '40 rsd', image: 'belihleb.jpg' },
    { name: 'Razeni hleb', category: 'peciva', price: '40rsd', image: 'kiflice-maslina.jpg' },
    { name: 'Tost hleb', category: 'peciva', price: '40 rsd', image: 'bakinhleb.jpg' }, 
    { name: 'Bakin hleb', category: 'peciva', price: '200e', image: 'tosthleb.jpg' },
    { name: 'Razeni hleb', category: 'peciva', price: '900 rsd', image: 'razenihleb.jpg' },
    { name: 'Beli hleb', category: 'peciva', price: '40 rsd', image: 'belihleb.jpg' },
    { name: 'Razeni hleb', category: 'peciva', price: '40rsd', image: 'kiflice-maslina.jpg' },
    { name: 'Tost hleb', category: 'peciva', price: '40 rsd', image: 'bakinhleb.jpg' }, 
    { name: 'Bakin hleb', category: 'peciva', price: '200e', image: 'tosthleb.jpg' },
    { name: 'Razeni hleb', category: 'peciva', price: '900 rsd', image: 'razenihleb.jpg' },
    { name: 'Beli hleb', category: 'peciva', price: '40 rsd', image: 'belihleb.jpg' },
    { name: 'Razeni hleb', category: 'peciva', price: '40rsd', image: 'kiflice-maslina.jpg' },
    { name: 'Tost hleb', category: 'peciva', price: '40 rsd', image: 'bakinhleb.jpg' }, 
    { name: 'Bakin hleb', category: 'peciva', price: '200e', image: 'tosthleb.jpg' },
    { name: 'Razeni hleb', category: 'peciva', price: '900 rsd', image: 'razenihleb.jpg' },
    { name: 'Beli hleb', category: 'peciva', price: '40 rsd', image: 'belihleb.jpg' },
    { name: 'Razeni hleb', category: 'peciva', price: '40rsd', image: 'kiflice-maslina.jpg' },
    { name: 'Tost hleb', category: 'peciva', price: '40 rsd', image: 'bakinhleb.jpg' }, 
    { name: 'Bakin hleb', category: 'peciva', price: '200e', image: 'tosthleb.jpg' },
    { name: 'Razeni hleb', category: 'peciva', price: '900 rsd', image: 'razenihleb.jpg' },
    { name: 'Beli hleb', category: 'peciva', price: '40 rsd', image: 'belihleb.jpg' },
    { name: 'Razeni hleb', category: 'peciva', price: '40rsd', image: 'kiflice-maslina.jpg' },
    { name: 'Tost hleb', category: 'peciva', price: '40rsd', image: 'tosthleb.jpg' }, 
    { name: 'Bakin hleb', category: 'peciva', price: '40rsd', image: 'tosthleb.jpg' },
    { name: 'Bakin hleb', category: 'peciva', price: '40rsd', image: 'tosthleb.jpg' },
    { name: 'Beli hleb', category: 'hleb', price: '40rsd', image: 'tosthleb.jpg' },
    { name: 'Razeni hleb', category: 'hleb', price: '40rsd', image: 'tosthleb.jpg' },
    { name: 'Tost hleb', category: 'peciva', price: '40rsd', image: 'tosthleb.jpg' }, 
    { name: 'Bakin hleb', category: 'peciva', price: '40rsd', image: 'tosthleb.jpg' },
    { name: 'Bakin hleb', category: 'peciva', price: '40rsd', image: 'tosthleb.jpg' },
    { name: 'Beli hleb', category: 'hleb', price: '40rsd', image: 'tosthleb.jpg' },
    { name: 'Razeni hleb', category: 'hleb', price: '40rsd', image: 'tosthleb.jpg' },
    { name: 'Tost hleb', category: 'peciva', price: '40rsd', image: 'tosthleb.jpg' }, 
    { name: 'Bakin hleb', category: 'peciva', price: '40rsd', image: 'tosthleb.jpg' },
    { name: 'Bakin hleb', category: 'peciva', price: '40rsd', image: 'tosthleb.jpg' },
    { name: 'Beli hleb', category: 'hleb', price: '40rsd', image: 'tosthleb.jpg' },
    { name: 'Razeni hleb', category: 'hleb', price: '40rsd', image: 'tosthleb.jpg' },
    { name: 'Tost hleb', category: 'peciva', price: '40rsd', image: 'tosthleb.jpg' }, 
    { name: 'Bakin hleb', category: 'peciva', price: '40rsd', image: 'tosthleb.jpg' },
    { name: 'Bakin hleb', category: 'peciva', price: '40rsd', image: 'tosthleb.jpg' },
    { name: 'Beli hleb', category: 'hleb', price: '40rsd', image: 'tosthleb.jpg' },
    { name: 'Razeni hleb', category: 'hleb', price: '40rsd', image: 'tosthleb.jpg' },
    { name: 'Tost hleb', category: 'peciva', price: '40rsd', image: 'tosthleb.jpg' }, 
    { name: 'Bakin hleb', category: 'peciva', price: '40rsd', image: 'tosthleb.jpg' },
    { name: 'Bakin hleb', category: 'peciva', price: '40rsd', image: 'tosthleb.jpg' },
    { name: 'Beli hleb', category: 'hleb', price: '40rsd', image: 'tosthleb.jpg' },
    { name: 'Razeni hleb', category: 'hleb', price: '40rsd', image: 'tosthleb.jpg' },
    { name: 'Tost hleb', category: 'peciva', price: '40rsd', image: 'tosthleb.jpg' }, 
    { name: 'Bakin hleb', category: 'peciva', price: '40rsd', image: 'tosthleb.jpg' },
    { name: 'Bakin hleb', category: 'peciva', price: '40rsd', image: 'tosthleb.jpg' },
    { name: 'Beli hleb', category: 'hleb', price: '40rsd', image: 'tosthleb.jpg' },
    { name: 'Razeni hleb', category: 'hleb', price: '40rsd', image: 'tosthleb.jpg' },
    { name: 'Tost hleb', category: 'peciva', price: '40rsd', image: 'tosthleb.jpg' }, 
    { name: 'Bakin hleb', category: 'peciva', price: '40rsd', image: 'tosthleb.jpg' },
    { name: 'Bakin hleb', category: 'peciva', price: '40rsd', image: 'tosthleb.jpg' },
    { name: 'Beli hleb', category: 'hleb', price: '40rsd', image: 'tosthleb.jpg' },
    { name: 'Razeni hleb', category: 'hleb', price: '40rsd', image: 'tosthleb.jpg' },
    { name: 'Tost hleb', category: 'peciva', price: '40rsd', image: 'tosthleb.jpg' }, 
    { name: 'Bakin hleb', category: 'peciva', price: '40rsd', image: 'tosthleb.jpg' },
    { name: 'Bakin hleb', category: 'peciva', price: '40rsd', image: 'tosthleb.jpg' },
    { name: 'Beli hleb', category: 'hleb', price: '40rsd', image: 'tosthleb.jpg' },
    { name: 'Razeni hleb', category: 'hleb', price: '40rsd', image: 'tosthleb.jpg' },
    { name: 'Tost hleb', category: 'peciva', price: '40rsd', image: 'tosthleb.jpg' }, 
    { name: 'Bakin hleb', category: 'peciva', price: '40rsd', image: 'tosthleb.jpg' },
    { name: 'Bakin hleb', category: 'peciva', price: '40rsd', image: 'tosthleb.jpg' },
    { name: 'Beli hleb', category: 'hleb', price: '40rsd', image: 'tosthleb.jpg' },
    { name: 'Razeni hleb', category: 'hleb', price: '40rsd', image: 'tosthleb.jpg' },
    { name: 'Tost hleb', category: 'peciva', price: '40rsd', image: 'tosthleb.jpg' }, 
    { name: 'Bakin hleb', category: 'peciva', price: '40rsd', image: 'tosthleb.jpg' },
    { name: 'Bakin hleb', category: 'peciva', price: '40rsd', image: 'tosthleb.jpg' },

    // { category: 'Hleb', products: [
    //     { name: 'Beli hleb', price: '40 rsd', image: 'tosthleb.jpg'},
    //     { name: 'Razeni hleb', price: '50 rsd', image: 'tosthleb.jpg'},
    //     { name: 'Tost hleb', price: '33 rsd', image: 'tosthleb.jpg'},
    //     { name: 'Bakin hleb', price: '70 rsd', image: 'tosthleb.jpg'},
    //     { name: 'Crni hleb', price: '40 rsd', image: 'tosthleb.jpg'},
    // ]}
];